version: '3.5'

services:
  app:
    image: app
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./wait-for-it.sh:/usr/src/app/wait-for-it.sh
    environment:
      - DATABASE_DSN=postgres://postgres:postgres@db:5432/praktikum?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: sh -c './wait-for-it.sh -t 5 db:5432 -- app'
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=praktikum
    ports:
      - '5432:5432'